/*import { CalendarComponent } from './Calendar/calendar.component';
import { NavMenuComponent } from './navmenu/navmenu.component';
import { HomeComponent } from './home/home.component';
import { UserListComponent } from './user-list/user-list.component';
import { ArticlesComponent } from './articles/articles.component';
import { AddArticleComponent } from './add-article/add-article.component';
import { LoginComponent } from './login/login.component';
import { NotficationsBarComponent } from './notfications-bar/notfications-bar.component';
import { AdminBarComponent } from './admin-bar/admin-bar.component';
import { AdminProfileComponent } from './admin-profile/admin-profile.component';
import { UserProfileComponent } from './user-profile/user-profile.component';
import { NgxSummernoteModule } from 'ngx-summernote';
import { AlertComponent } from './alert/alert.component';*/